name: DJJMorgan
favicon: null
layout_spectrum: 0.2634717442560941
typography_spectrum: 0.41027276148088276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1feec'
    - '#180016'
    - '#99bdd3'
    - '#6072a2'
    - '#3f395d'
  brandStrength: 0.11548705166205764
  lightness: 0.19051319058053195
  saturation: 0.8546235831454396
  rhythmicContrast: 0.7474775197915733
purpose: []
